### PR TITLE
hebrew for FARL (solves issue #6)

### PR DESCRIPTION
**Pull request by jocker-il**
made a hebrew locale file. inverted it so it is visable in 0.11.x and 0.12

 for 0.12.1 I need to uninvert it because there will be a code change in-game to invert the text that the devs will make

### CODE REVIEW

**Comment by Choumiko** [comment]
can you create another pull request for the 0.12.1 version? I doubt anyone is going to use 0.12.0, now that 0.12.1 is out

**Comment by jocker-il** [comment]
Do you believe I haven't had time to even test hebrew on the 0.12 yet ?

 I'm worried what the changes will do to my current savegame

**Comment by Choumiko** [comment]
I didn't mean to put any pressure on you. I just assumed that you already have an uninverted file with the translations. I know nothing about the problems with RTL languages in Factorio, so take all the time you need. Is uninverting as simple as turning "txet sihT" into "This text"?

**Comment by jocker-il** [comment]
a. it is as simple as that, but
b. I have to do it for every string in the file and that takes time...

 I meant to do it today, but I'm not good at organizing my time and I work Sunday to Friday, so I didn't have the time today. Also, I like to test my work before submitting it for review.

 I will do this now, might finish in an hour

**Comment by jocker-il** [comment]
I'm sorry to report that I have work for you:

the on-screen display of FARL frond and back-end text is not translatable. also - why is the frond end "last" ?
farl on screen text

the error text not translatable (I know it's just for negative-root, but it might be opened to other users some day (as we discussed) and it's bad practice, as I understand it (not judging !) to have hard-coded text strings)

farl ngtv-root mode

 I made a separate issue for each,

 Also, I have a new Hebrew translation for the current version (0.3.13) I'm looking into syncing with your master instead of replicating it to me, working on my copy of master and then asking you to pull (I think that syncing with the master saves replicas and still requires me to make a pull request)

**Comment by Choumiko** [comment]
I'll figure out how to give you rights to commit directly tomorrow, seems like less work for both of us. Hebrew looks soooo confusing to european eyes :-)

**Pull request closed without merging**
